### ISSUE TITLE
plugin-image-optimization 插件实例引用时 optmizer 少了一个 i (optimizer)

### ISSUE THREAD

**Issue by dxhuii** [Atyantik/react-pwa#102] opened 2018-08-30 09:08 UTC
https://www.reactpwa.com/docs/en/plugin-image-optimization.html

实例错了：
原：import ImageOptimizer from "@pawjs/image-optmizer/webpack";
正确的：import ImageOptimizer from "@pawjs/image-optimizer/webpack";

optmizer 少了一个 i (optimizer)

![](https://ws1.sinaimg.cn/large/006bnWk0gy1furub69h5oj31a412owka.jpg)

**Comment by tirthbodawala** [comment] 2018-08-30 09:47
@dxhuii we have merged your PR and thus the issue is resolved. Thanks for finding it out.

**Closed by tirthbodawala** 2018-08-30 09:47 UTC
